# Generated by Django 4.2 on 2024-04-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.channel'),
        ),
        migrations.AddField(
            model_name='episode',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='episode_comments', to='content.comment'),
        ),
        migrations.AddField(
            model_name='episode',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_episodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episode',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='episode_links', to='content.link'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
