# Generated by Django 4.2 on 2024-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_alter_channel_episode_count_subscriptions'),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to='user_dashboard.channel'),
        ),
    ]
