# Generated by Django 4.2 on 2024-04-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='follower_count',
        ),
    ]
