# Generated by Django 4.2 on 2024-04-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_activities', '0001_initial'),
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.channel'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_activities.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AddField(
            model_name='newepisode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.channel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
