# Generated by Django 4.2 on 2024-04-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
        ('user_activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='podcasts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.channel'),
        ),
    ]
